[Mon Oct 18 18:58:17 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26526, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 18:58:18 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26533, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26533): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 13:58:19 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26526): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 141, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 13:58:20 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 18:58:20 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26527, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26527): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 13:58:21 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 19:02:18 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26576, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 19:02:19 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26581, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26581): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 19:02:19 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26576): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 141, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:02:21 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 19:02:21 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26578, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26578): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 19:02:21 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 19:12:11 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26580, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26578): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 14:12:13 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 19:12:16 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26579, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 19:12:16 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26577, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/new_competition/
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26579): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 14:12:18 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 19:12:24 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26583, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 19:12:24 2010] [info] [client 24.98.197.10] mod_wsgi (pid=26582, process='', application='www.ec2-67-202-0-100.compute-1.amazonaws.com|'): Loading WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26582): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26583): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26576): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 14:12:25 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26580): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26583): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26582): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26581): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26579): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26576): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26578): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info()), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template., referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name), referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html, referer: http://ec2-67-202-0-100.compute-1.amazonaws.com/admin/competition/competition/
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26580): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 14:12:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10] mod_wsgi (pid=26577): Exception occurred processing WSGI script '/var/www/bizmodelcomp/apache/django.wsgi'.
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10] Traceback (most recent call last):
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]     response = self.get_response(request)
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 130, in get_response
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 180, in handle_uncaught_exception
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]     return callback(request, **param_dict)
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 23, in server_error
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]     t = loader.get_template(template_name) # You need to create a 500.html template.
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 157, in get_template
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]     template, origin = find_template(template_name)
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]   File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in find_template
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10]     raise TemplateDoesNotExist(name)
[Mon Oct 18 14:55:29 2010] [error] [client 24.98.197.10] TemplateDoesNotExist: 500.html
